---
version: 1.4.0
default-factions-plugin: FactionsPro
groups:
  Guest:
    chat: §6[§f{fac_name}§6] §e•»§fMember§e«• §3{display_name} §b» §f{msg}
    nametag: §6[§f{fac_name}§6] §e•»§fMember§e«• §3{display_name}
    worlds: []
  Admin:
    nametag: §6[§f{fac_name}§6] §e۩§6…§r§dΛ§cɖ§aɱ§eɨ§bɲ§l§6…§e۩  §r§l§c{display_name}
    chat: §b•§6[§f{fac_name}§6] §e۩§6…§r§dΛ§cɖ§aɱ§eɨ§bɲ§l§6…§e۩  §r§l§c{display_name}
      §r§d⊹⊱✿ §c{msg} §r§d✿
  Owner:
    chat: §b•§6[§f{fac_name}§6] §b♫§d…§e★§aØwner§e★§d…§b♫ §c{display_name} §f§l⇨§r
      §3{msg} §f§l⇦
    nametag: §6[§f{fac_name}§6] §e»…§cᄉ§7→§cØwner§7←§cᄉ§e…§e« §b{display_name}
    worlds: []
  Trùm:
    chat: §b•§6[§f{fac_name}§6] §e♠§a...§c❤§bŦřùm§c❤§a...§e♠ §bNguyên§r §e⇨ §a{msg}
      §e⇦
    nametag: §6[§f{fac_name}§6] §e»…§cᄉ§7→§cBoss§7←§cᄉ§e…§e« §b{display_name}
  Helper:
    chat: §b•§6[§f{fac_name}§6] §d✿§c...§aĦełper§c...§d✿§6» §r{display_name} §6«§a♫§e⇛
      §a{msg} §e⇚
    nametag: §6[§f{fac_name}§6] §e»§6…§d「§7→§aHelper§7←§d」§6…§e« §f{display_name}
    worlds: []
  Builder:
    chat: §b•§6[§f{fac_name}§6] §c❖§a...§d❦§6ɮʊɨŁđɛɾ§d❦§a...§c❖ §b{display_name} §5⇥
      §a{msg} §5⇤
    nametag: §6[§f{fac_name}§6] §e»…§6♨§7→§6Builder§7←§6♨§e…§e« §f{display_name}
  Police:
    chat: §b•§6[§f{fac_name}§6] §c✇§6...§a❂§bΡølice§a❂§6...§c✇§f⇨§a§l{display_name}§r§e➟
      §e{msg}
    nametag: §6[§f{fac_name}§6] §e»§6…§9✪§7→§9₱olice§7←§9✪§6…§e« §f{display_name}
  Youtube:
    chat: §b•§6[§f{fac_name}§6] §e»§6…§4❤§b♪§cYδμ§fṯüḇε§b♪§4❤§6…§e« §f{display_name}
      §6√ §c{msg} §6√
    nametag: §6[§f{fac_name}§6] §e»§6…§4❤§b♪§cYδμ§fṯüḇε§b♪§4❤§6…§e« §f{display_name}
  PMem:
    chat: §b•§6[§f{fac_name}§6] §e»§a…§fƸ§7→§bṔrσ_ᙢember§7←§fƷ§a…§e« §f{display_name}
      §e⇝ §f{msg} §e⇜
    nametag: §6[§f{fac_name}§6] §e»§a…§fƸ§7→§bṔrσ_ᙢember§7←§7Ʒ§a…§e« §f{display_name}
  1:
    nametag: §6[§b{fac_name}§6]§e»§f..₪§e♦§6›§bVIP§d-§eI§6‹§e♦§f₪.. §e« §f{display_name}§e⇝
      §o§6{msg} §e⇜
    chat: §6[§b{fac_name}§6]§e»§f..₪§e♦§6›§bVIP§d-§eI§6‹§e♦§f₪.. §e« §f{display_name}§e⇝
      §o§6{msg} §e⇜
  2:
    nametag: §6[§b{fac_name}§6]§e»§f..₪§e♦§6›§bVIP§d-§eII§6‹§e♦§f₪.. §e« §f{display_name}§e⇝
      §o§6{msg} §e⇜
    chat: §6[§b{fac_name}§6]§e»§f..₪§e♦§6›§bVIP§d-§eII§6‹§e♦§f₪.. §e« §f{display_name}§e⇝
      §o§6{msg} §e⇜
  3:
    nametag: §6[§b{fac_name}§6]§e»§f..₪§e♦§6›§bVIP§d-§eIII§6‹§e♦§f₪.. §e« §f{display_name}§e⇝
      §o§6{msg} §e⇜
    chat: §6[§b{fac_name}§6]§e»§f..₪§e♦§6›§bVIP§d-§eIII§6‹§e♦§f₪.. §e« §f{display_name}§e⇝
      §o§6{msg} §e⇜
  4:
    nametag: §6[§b{fac_name}§6]§e»§f..₪§e♦§6›§bVIP§d-§eIV§6‹§e♦§f₪.. §e« §f{display_name}§e⇝
      §o§6{msg} §e⇜
    chat: §6[§b{fac_name}§6]§e»§f..₪§e♦§6›§bVIP§d-§eIV§6‹§e♦§f₪.. §e« §f{display_name}§e⇝
      §o§6{msg} §e⇜
  5:
    nametag: §6[§b{fac_name}§6]§e»§f..₪§e♦§6›§bVIP§d-§eV§6‹§e♦§f₪.. §e« §f{display_name}§e⇝
      §o§6{msg} §e⇜
    chat: §6[§b{fac_name}§6]§e»§f..₪§e♦§6›§bVIP§d-§eV§6‹§e♦§f₪.. §e« §f{display_name}§e⇝
      §o§6{msg} §e⇜
  Co-OP:
    nametag: '&8&l[Co-OP]&f&r {display_name}'
    chat: '&8&l[Co-OP]&f&r {display_name} &7> {msg}'
  Youtuber:
    nametag: '&8&l[Youtuber]&f&r {display_name}'
    chat: '&8&l[Youtuber]&f&r {display_name} &7> {msg}'
  vip1:
    chat: §6[§b{fac_name}§6]§e»§f..₪§e♦§6›§bVIP§d-§eɪ§6‹§e♦§f₪.. §e« §f{display_name}§e⇝
      §o§6{msg} §e⇜
    nametag: '&8&l[vip1]&f&r {display_name}'
  BestBuilder:
    nametag: '&8&l[BestBuilder]&f&r {display_name}'
    chat: '&8&l[BestBuilder]&f&r {display_name} &7> {msg}'
  YT:
    nametag: '&8&l[YT]&f&r {display_name}'
    chat: '&8&l[YT]&f&r {display_name} &7> {msg}'
  PMember:
    nametag: '&8&l[PMember]&f&r {display_name}'
    chat: '&8&l[PMember]&f&r {display_name} &7> {msg}'
  Coder:
    chat: §d•§c[§e{fac_name}§c] §e♠§b...§c❤§bJɑɨłєɖ§c❤§b...§e♠ §cBảo§r §b⇨ §d{msg} §b⇦
    nametag: §6[§f{fac_name}§6] §e»…§cᄉ§7→§cBoss§7←§cᄉ§e…§e« §b{display_name}
  §l§eÖ§6c§esÇ§6ho§es:
    nametag: §b•§6[§f{fac_name}§6] §e♠§a...§c❤§dQʊý_Tộℭ§c❤§a...§e♠ §cKì§r
    chat: §b•§6[§f{fac_name}§6]§e♠§a...§c❤§dQʊý_Tộℭ§c❤§a...§e♠ §cKì§r §e⇨ §a{msg}
      §e⇦
  Superman:
    chat: §6[§b{fac_name}§6] §1§l☆§r...§1Şupeř§fman...§1§l☆ §f§l=Apin= §1§l-§r§o{msg}§1§l-
    nametag: '&8&l[Superman]&f&r {display_name}'
  quytoc:
    nametag: §b•§6[§f{fac_name}§6] §e♠§a...§c❤§dQʊý_Tộℭ§c❤§a...§e♠ §cKì§r
    chat: §b•§6[§f{fac_name}§6]§e♠§a...§c❤§dQʊý_Tộℭ§c❤§a...§e♠ §cKì§r §e⇨ §a{msg}
      §e⇦
  MP:
    chat: §6[§f{fac_rank}{fac_name}§6] §b•…♦§cMilitary§6♠§aPolice§b♦…•§f {display_name}§b
      ->§a {msg}
    nametag: §6[§f{fac_rank}{fac_name}§6] §b•…♦§cMilitary§6♠§aPolice§b[§c+§b]♦…•§f
      {display_name}
...
