---
datetime-format: "H:i:s"
Motd:
  update-timeout: 1
  custom: false
  message: "&e[{TIME}] &aChào mừng bạn đã đến với §4Zero§6Sky! &n&b[{TOTALPLAYERS}/{MAXPLAYERS}]"
OutdatedClient:
  custom: true
  message: "&cPhiên bản mcpe bạn đã cũ!Hãy tải bạn mới!"
OutdatedServer:
  custom: true
  message: "&cServer đang trong phiên bản cũ!"
WhitelistedServer:
  custom: true
  message: "&c&oThis Server is whitelisted!"
FullServer:
  custom: false
  message: "&e{PLAYER}&b, The Server is full &c[{TOTALPLAYERS}/{MAXPLAYERS}]&b!\n&l&dTry to join later :)"
FirstJoin:
  enable: true
  message: "§a{PLAYER} Tham Gia Server Lần đầu"
Join:
  hide: false
  custom: true
  message: "§6[§b+§6]§6{PLAYER} đã tham gia vào Server"
Quit:
  hide: false
  custom: true
  message: "§6[§b-§6]§4{PLAYER} đã rời khỏi Server :<"
WorldChange:
  enable: false
  hide: true
  message: "&a{PLAYER}&e Đã Di Chuyển Từ &c{ORIGIN}&e Đến &a{TARGET}"
Death:
  hide: false
  custom: true
  message: "&c{PLAYER} Đã chết!"
  death-contact-message:
    hide: true
    custom: true
    message: "&cOops! {PLAYER} was killed by {BLOCK}"
  kill-message:
    hide: false
    custom: true
    message: "&9{PLAYER} &6Đã bị &c{KILLER} hiếp :>"
  death-projectile-message:
    hide: false
    custom: true
    message: "&c{PLAYER} Bị {KILLER} bắn chết"
  death-suffocation-message:
    hide: true
    custom: true
    message: "&c{PLAYER} suffocated"
  death-fall-message:
    hide: true
    custom: true
    message: "&c{PLAYER} fell from a high place"
  death-fire-message:
    hide: true
    custom: true
    message: "&c{PLAYER} chơi dung nham :v"
  death-on-fire-message:
    hide: true
    custom: true
    message: "&c{PLAYER} nghịch lửa và tìm đường cứu nước"
  death-lava-message:
    hide: true
    custom: true
    message: "&c{PLAYER} bơi tren dung nham :v"
  death-drowning-message:
    hide: true
    custom: true
    message: "&c{PLAYER} drowned"
  death-explosion-message:
    hide: false
    custom: true
    message: "&c{PLAYER} bị bổ banh xác"
  death-void-message:
    hide: true
    custom: true
    message: "&c{PLAYER} fell into the void"
  death-suicide-message:
    hide: true
    custom: true
    message: "&c{PLAYER} committed suicide"
  death-magic-message:
    hide: false
    custom: true
    message: "&c{PLAYER} bị ung thư giai đoạn cuối :v"
...
