---
show-messages-onjoin: true
force-hub: false
enable-hub-message: true
force-spawn: false
enable-spawn-message: true
enable-aliases: true
teleport-on-death: 1
hub-server:
  enabled: false
  name: External Server
  host: 127.0.0.1
  port: 19132
hub:
  world: Hub
  X: -96.407500
  "Y": 75.000000
  Z: 93.401100
  Yaw: 88.331696
  Pitch: 56.248657
...
